name = "GlycolysisPentosePathwayPhaseMap"
uuid = "375dfa41-524f-41be-aa55-8aa929d49439"
authors = ["James Mbata"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
